[package]
name = "scutter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "1"
log = "0.4"
reqwest = "0.11"
tokio = "1"
url = "2"
